name: 'Setup Python with uv'
description: 'Set up Python environment with uv and install dependencies'

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      
    - name: Set up Python
      shell: bash
      run: uv python install
      
    - name: Install dependencies
      shell: bash
      run: uv sync