name: "Setup Python with uv"
description: "Set up Python environment with uv and install dependencies"

inputs:
  python-version:
    description: "Python version to install"
    required: false
    default: "3.10"

runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Set up Python
      shell: bash
      run: uv python install ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: uv sync
