name: Auto Release

on:
  push:
    branches: [main]
    paths:
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  check-version-change:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.version_check.outputs.changed }}
      new_version: ${{ steps.version_check.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Need previous commit to compare

      - name: Setup environment
        uses: ./.github/actions/setup-uv-python

      - name: Check if version changed
        id: version_check
        run: |
          # Get current version
          CURRENT_VERSION=$(uv run bump-my-version show current_version)
          echo "Current version: $CURRENT_VERSION"

          # Check if pyproject.toml changed in the last commit
          if git diff HEAD~1 HEAD --name-only | grep -q "pyproject.toml"; then
            echo "Version file changed"
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Version file not changed"
            echo "changed=false" >> $GITHUB_OUTPUT
          fi

  run-tests:
    needs: check-version-change
    if: needs.check-version-change.outputs.version_changed == 'true'
    uses: ./.github/workflows/checks.yml

  create-release:
    needs: [check-version-change, run-tests]
    if: needs.check-version-change.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check-version-change.outputs.new_version }}
          release_name: Release v${{ needs.check-version-change.outputs.new_version }}
          body: |
            ## What's Changed
            Version bump to v${{ needs.check-version-change.outputs.new_version }}

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/v${{ needs.check-version-change.outputs.new_version }}...v${{ needs.check-version-change.outputs.new_version }}
          draft: false
          prerelease: false

  build-and-publish:
    needs: [create-release, check-version-change]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-uv-python

      - name: Build package
        run: uv build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
