name: Auto Release

on:
  push:
    branches: [main]
    paths:
      - "pyproject.toml"
  workflow_dispatch:
    inputs:
      force_release:
        description: 'Force release'
        type: boolean
        default: false

permissions:
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup environment
        uses: ./.github/actions/setup-uv-python

      - name: Get version
        id: version
        run: |
          VERSION=$(uv run bump-my-version show current_version)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Current version: $VERSION"

      - name: Check if release needed
        id: check
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          FORCE="${{ github.event.inputs.force_release }}"
          
          # Check if tag exists using GitHub API
          if curl -s "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/v$VERSION" | grep -q '"ref"'; then
            echo "Tag v$VERSION already exists"
            SHOULD_RELEASE="false"
          else
            echo "Tag v$VERSION does not exist"
            SHOULD_RELEASE="true"
          fi
          
          # Override if forced
          if [[ "$FORCE" == "true" ]]; then
            echo "Release forced"
            SHOULD_RELEASE="true"
          fi
          
          echo "should_release=$SHOULD_RELEASE" >> $GITHUB_OUTPUT

      - name: Run tests
        if: steps.check.outputs.should_release == 'true'
        uses: ./.github/workflows/checks.yml

      - name: Build package
        if: steps.check.outputs.should_release == 'true'
        run: uv build

      - name: Create release
        if: steps.check.outputs.should_release == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: Release v${{ steps.version.outputs.version }}
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PyPI
        if: steps.check.outputs.should_release == 'true'
        uses: pypa/gh-action-pypi-publish@release/v1